//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.28 at 02:16:25 PM MSK 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.winter-market.com/spring/products", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.geelbrains.spring.winter.market.soap.products;
